# Generated by Django 4.2.13 on 2024-10-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_moviedata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='Images/Noimg.jpg', upload_to='Images/'),
        ),
    ]
