# Generated by Django 4.2.18 on 2025-01-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_consume'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='fats',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
