# Generated by Django 4.2.16 on 2024-11-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='order',
            name='lname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
